# Generated by Django 5.2.13 on 2026-04-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='post',
        ),
    ]
